### ISSUE TITLE
result.dimension error in quandl_to_db

### ISSUE THREAD

**Issue by ghost** [carstenf/Security-Master#1]
at line 495 in the function fill_fundamental_data, i get an error:
'DataFrame' object has no attribute 'dimension'.

`
            result3 = result.loc[result.dimension == 'ARY']
            result2 = result.loc[result.dimension == 'ARQ' ]
            
result1 = result.loc[result.dimension == 'ART' ]`    

what do you mean by dimension? shape/size/dimn

**Comment by carstenf** [comment]
are you using Quandl withs this package Core US Fundamentals Data PUBLISHED BY SHARADAR?

It looks like you don't have fundamental data.
Dimension is ARQ, ARY, ART, MRT.... it's the reporting period AS REPORTED QUATERLY ARQ

**Comment by carstenf** [comment]
pls check link https://www.quandl.com/databases/SF1/data and see the header of the Core US Fundamentals https://www.quandl.com/tables/SF1/SHARADAR-SF1 with dimension.

**Comment by carstenf** [comment]
can I close this?

**Comment by ghost** [comment]
yes, the fundamental data was't available for free so i got the error, thanks.

**Comment by carstenf** [comment]
ok, good to know, but you can use yahoo as well to fill the database. the only issue is the ticker list. but you can download a ticker list from quandl for free from that bundle I mentioned. than generate the ticker list, I put an example in the repo. than use it with the yahoo_to_db.py

if you want to use the free quandl, you need to comment some call in the main, just at the end of the file quandl_to_db.py

or you get the full package for one month for around 99$....and you can use this database with the alphacompiler to use fundamental data with zipline, just building it :)

**Comment by ghost** [comment]
Hi thanks for the support. I'm just starting out with algorithmic trading
and want to test some things before paying for a vendor. Does the full
package and quandl_to_db.py include delisted stocks?

**Comment by carstenf** [comment]
yes! yahoo, I believe does not, or not for many years. I got the one from Quandl for 20years, I think you can get shorter period for less.
which backtester you are planing to use?

**Comment by carstenf** [comment]
of course there are better data than Quandl, like factset, Bloomberg, Morningstar but the cost a fortune...

**Comment by ghost** [comment]
99$ isn't really that expensive so I will think ill go for it. can i pay
for a month download the data to the database and then not continue with
them? or do i have to delete the data?

**Comment by carstenf** [comment]
can i pay
for a month download the data to the database and then not continue with
them?        

thats what I did.

which backtester you are going to use? zipline?

**Comment by ghost** [comment]
Yes, Zipline looks really great and simple to understand. I'm planning on
backtesting some strategies with it and then connect my
brokerage(Interactive brokers) and update the database with their data.

**Comment by carstenf** [comment]
ok, first zipline only works with price, no fundamentals. -> for this I found a solution > alphacompiler
second, you can't connect it to a broker -> for this not yet -> did you found something?
did you already install zipline?...it was not that easy for me

**Comment by carstenf** [comment]
...are you using Mac or windows?

**Comment by ghost** [comment]
Yep I'm kind of working with 2 friends and it was really pain in the ass to
get the environment working but it's worth it. I'm working on windows, did
it with anaconda and it really simplified things.

**Comment by carstenf** [comment]
...ok, i was thinking to put everything into dockers, but it will probably only work on the same operating system, I'm on Mac

**Comment by carstenf** [comment]
basically you need:
- zipline
- an interface between data vendor and zipline -> can use my database
- an additional tool to get fundamental data running on zipline -> alphacompiler, and I need to publish my bridge between alphaxompiler and my database
(with this you get fundamental data, sector code and S&P500 member filter
- than you need a bridge to  Interactive brokers-> im still looking as well...
..and if everything is ready, someone needs to put it into dockers...

**Comment by ghost** [comment]
Hi, hope you are doing well.
I decided to buy Sharadar bundle so i try to load the data into my database
and i get comments that some price data is missing. in your load did you
encounter this too?

**Comment by carstenf** [comment]
Yes, that’s normal. 
The program first reads the list of tickets from quandl.
Based on that list, it reads the price data. If that ticker is not in the list of price data included, you get the massage.
Was it difficult until here?

Best
Carsten 


Am 18.04.2020 um 15:54 schrieb MasterKaido <notifications@github.com>:
> 

﻿
Hi, hope you are doing well.
I decided to buy Sharadar bundle so i try to load the data into my database
and i get comments that some price data is missing. in your load did you
encounter this too?

**Comment by ghost** [comment]
thought about adding insider transactions and funds prices that comes with
shradar bundle?

**Comment by carstenf** [comment]
﻿
thought about adding insider transactions -> is that included? Which table?

and funds prices that comes with
shradar bundle? -> you can include them already. 
Try to understand how the quandl_to_db works.
Funds are already in the ticker list, that’s the security table.
Than you need to add to the code, that it needs as well to include the ttable for funds, it’s probably SF3???, in the section were you read the pricing. Now it reads only SF1.
Later you have to include this as well in the header of the db_to_bundle

I hope it’s not too difficult 


> Am 19.04.2020 um 10:41 schrieb MasterKaido <notifications@github.com>:

﻿
thought about adding insider transactions and funds prices that comes with
shradar bundle?
